courseSelect/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
    # url(r'^$', views.?, name='?'),
    url(r'^courses/$',views.courses,name="courses"),
    url(r'^select', views.select, name="select"),
    url(r'^table', views.table, name="table"),
    url(r'^teacher', views.teacher, name="teacher"),
    url(r'^curriculum/',views.curriculum, name="curriculum"),
    url(r'^course_select/$',views.course_select,name="course_select"),
    url(r'^export',views.export_excel,name="export"),
    url(r'^control_panel/', views.control, name="control"),
    url(r'^import_student/', views.import_student, name="import"),
    url(r'^api/disciplines_options/get', views.get_discipline_options, name="get_discipline_options"),
    url(r'^api/disciplines_details/post',views.post_discipline_details, name="post_discipline_details"),
    url(r'^api/disciplines_details/get',views.get_discipline_details, name="get_discipline_details"),
    url(r'^api/courses/get', views.get_all_courses, name="get_all_course"),
    url(r'^api/required_courses/get', views.get_required_courses, name="get_required_courses"),
    url(r'^api/required_course/delete', views.remove_required_course, name="remove_required_course"),
]

forum/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.home, name='forum'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/list/$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
    url(r'^post/search/$', views.post_search, name='post_search'),
    url(r'^reply/new/(?P<pk>[0-9]+)/$', views.reply_new, name='reply_edit'),
    url(r'^bulletin/new/$', views.bulletin_new, name='bulletin_new'),
    url(r'^message/new/$', views.message_new, name='message_new'),
    url(r'^message/send$', views.message_send, name='message_send'),
    url(r'^message/receive/$', views.message_receive, name='message_receive'),
    url(r'^upload/(?P<pk>[0-9]+)/$', views.upload, name='upload'),
    url(r'^download/(?P<pk>[0-9]+)/$', views.file_down, name='download'),
]

jwsystem/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'jwsystem.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    
    url(r'^admin/', include(admin.site.urls)),
    url(r'^course_select/', include('courseSelect.urls')),
    url(r"^basic/",include('basicInfo.urls')),
    url(r"^api/",include('basicInfo.apiUrls')),
    url(r'^forum/', include('forum.urls')),
    url(r'^course_arrange/', include('courseArrange.urls')),
    url(r'^online_test/', include('onlineTest.urls', namespace='online_test'))
]

basicInfo/models.py
from django.db import models
from basicInfo.config import course_type

class observer:
    def __init__(self):
        pass
    def update(self,*text):
        pass

class OperationObserver(observer):
    def update(self,*text):
        operation.objects.create(description=text[0])
        print("log saved")

class TeacherObserver(observer):
    def update(self,*text):
        teacher.objects.create(*text)


class account(models.Model):
    '''
    accout(accout_id int, password varchar(20) not null) //统一账户
    '''

    observers=[OperationObserver(),TeacherObserver()]  # observer list
    account_id=models.CharField(max_length=20,primary_key=True)
    password=models.CharField(max_length=200,null=False)
    salt=models.CharField(max_length=8,null=False,default="12345678")
    type=models.IntegerField(null=False,default=0)
    
    def save(self, *args, **kwargs):
        print("account saved")
        super(account, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.account_id


class attrib(models.Model):
    '''
    attrib(account_id int, nickname varchar(40), picture varchar(40)), email varchar(40), exp int, coin int) //账户属性 ref account
    '''

    account_id=models.ForeignKey(account,on_delete=models.CASCADE,primary_key=True)
    nickname=models.CharField(max_length=40,null=False)
    picture=models.ImageField(upload_to="basicInfo/static/basicInfo/picture",null=True)
    email=models.CharField(max_length=40,null=True)
    exp=models.IntegerField(null=True)
    coin=models.IntegerField(null=True)


class student(models.Model):
    '''
    student(student_id int, name varchar(20) not null, dorm varchar(40)) //学生
    '''

    student_id=models.CharField(max_length=20,primary_key=True)
    name=models.CharField(max_length=20,null=False)
    dorm=models.CharField(max_length=40)
    grade=models.IntegerField(default=1)


class college(models.Model):
    '''
    college(college_id int, name varchar(40) not null, intro text) //学院
    '''

    college_id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=40,null=False)
    intro=models.TextField()


class discipline(models.Model):
    '''
    discipline(discipline_id int, name varchar(40) not null, intro text) //专业
    '''

    discipline_id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=40,null=False)
    intro=models.TextField()


class major(models.Model):
    '''
    major(student_id int, discipline_id int) //主修 ref student, discipline
    '''

    student_id=models.CharField(max_length=20,primary_key=True)
    discipline_id=models.IntegerField()
    class Meta:
        unique_together = ("student_id", "discipline_id")
    primary = ("student_id", "discipline_id")


class minor(models.Model):
    '''
    minor(student_id int, discipline_id int) //辅修 ref student, discipline
    '''

    student_id=models.CharField(max_length=20,primary_key=True)
    discipline_id = models.IntegerField()
    class Meta:
        unique_together = ("student_id", "discipline_id")
    primary = ("student_id", "discipline_id")


class belong(models.Model):
    '''
    belong(major_id int, college_id int) //专业所在学院 ref major, college
    '''

    discipline_id=models.ForeignKey(discipline,on_delete=models.CASCADE)
    college_id=models.ForeignKey(college,on_delete=models.CASCADE)
    class Meta:
        unique_together = ("discipline_id", "college_id")
    primary=("discipline_id", "college_id")


class course(models.Model):
    '''
    course(course_id int, name varchar(40) not null, credit real not null, capacity int not null, intro text, type varchar(40) not null) //课程
    '''

    course_id=models.CharField(max_length=10,primary_key=True)
    name=models.CharField(max_length=40,null=False)
    credit=models.DecimalField(max_digits=3,decimal_places=1)
    hour=models.FloatField()
    intro=models.TextField()
    duplicate = models.IntegerField(default=0)
    type=models.CharField(max_length=40,null=False,choices=course_type,default="0")
    semester=models.CharField(max_length=10,null=False,default="Spring")
    exam_date = models.DateTimeField(null=True)

class pre(models.Model):
    '''
    pre(tmp_course_id int, pre_course_id int) //课程预修 ref course
    '''
    tmp_course_id=models.IntegerField()
    pre_course_id=models.ForeignKey(course,on_delete=models.CASCADE)
    class Meta:
        unique_together=("tmp_course_id","pre_course_id")
    primary = ("tmp_course_id","pre_course_id")


class room(models.Model):
    '''
    room(room_id int, capacity int not null, location varchar(40) not null, type varchar(40) not null) //教室
    '''
    room_id=models.AutoField(primary_key=True)
    capacity=models.IntegerField(null=False)
    location=models.CharField(max_length=40,null=False)
    type=models.CharField(max_length=40,null=False)


class learn(models.Model):
    '''
    learn(student_id int, course_id int, grade int, status int) //参加课程 ref student, course
    '''

    student_id=models.ForeignKey(student,on_delete=models.CASCADE)
    course_id=models.ForeignKey(course,on_delete=models.CASCADE)
    grade=models.IntegerField(null=True)
    status=models.IntegerField(null=False,default=0)
    class Meta:
        unique_together=("student_id","course_id")
    primary=("student_id","course_id")


class time(models.Model):
    '''
    time(time_id int ,start time not null, end time not null, day int not null) // 时间段 const
    '''

    time_id=models.AutoField(primary_key=True)
    start=models.TimeField(null=False)
    end=models.TimeField(null=False)
    day=models.IntegerField(null=False)


class teacher(models.Model):
    '''
    teacher(teacher_id int, name varchar(20) not null) //教师
    '''

    teacher_id=models.ForeignKey(account,on_delete=models.CASCADE,related_name="teacherId",primary_key=True)
    name=models.CharField(max_length=20,null=False)
    title=models.CharField(max_length=10,null=False,default="lecturer")
    office=models.CharField(max_length=40,null=False)
    management=models.CharField(max_length=40,null=True)


class teach(models.Model):
    '''
    teach(teacher_id int, course_id int) //讲授课程 ref teacher, course
    '''

    teach_id=models.AutoField(primary_key=True)
    teacher_id=models.ForeignKey(teacher,on_delete=models.CASCADE,related_name="teacher_id_1")
    course_id=models.ForeignKey(course,on_delete=models.CASCADE,related_name="college_id_1")
    capacity=models.IntegerField(null=False)
    duplicate=models.IntegerField(default=1)


class readyteach(models.Model):
    '''
    readyteach(teacher_id int, course_id int) //讲授课程 ref teacher, course
    '''

    teacher_id=models.ForeignKey(teacher,on_delete=models.CASCADE)
    course_id=models.ForeignKey(course,on_delete=models.CASCADE)
    capacity=models.IntegerField(null=False)


class takeup(models.Model):
    '''
    takeup(course_id int, time_id int, room_id int, type int not null) //课程时空信息 ref course, time, room
    '''

    teach_id=models.ForeignKey(teach,on_delete=models.CASCADE)
    time_id=models.ForeignKey(time,on_delete=models.CASCADE)
    room_id=models.ForeignKey(room,on_delete=models.CASCADE)
    teacher_id=models.ForeignKey(teacher,on_delete=models.CASCADE)
    class Meta:
        unique_together = ("teach_id", "time_id","room_id")
    primary = ("teach_id", "time_id","room_id")


class examination(models.Model):
    '''
    exam(student_id int, takeup_id int, position int)//考生座位信息 ref student, takeup
    '''

    student_id=models.ForeignKey(student,on_delete=models.CASCADE)
    takeup_id=models.ForeignKey(takeup,on_delete=models.CASCADE)
    position=models.IntegerField(null=True)
    class Meta:
        unique_together = ("student_id", "takeup_id","position")
    primary = ("student_id", "takeup_id","position")


class evaluate(models.Model):
    '''
    evalueate(student_id int, teacher_id int, point real not null, description text) //学生评价 ref student, teacher
    '''
    student_id=models.ForeignKey(student,on_delete=models.CASCADE)
    teacher_id=models.ForeignKey(teacher,on_delete=models.CASCADE)
    point=models.DecimalField(max_digits=3,decimal_places=2)
    description=models.TextField()
    class Meta:
        unique_together = ("student_id", "teacher_id")
    primary = ("student_id", "teacher_id")


class work(models.Model):
    '''
    work(teacher_id int, college_id int) //归属学院 ref teacher, college
    '''

    teacher_id=models.ForeignKey(teacher,on_delete=models.CASCADE)
    college_id=models.ForeignKey(college,on_delete=models.CASCADE)
    class Meta:
        unique_together = ("teacher_id","college_id")
    primary = ("teacher_id","college_id")


class master(models.Model):
    '''
    master(teacher_id int, college_id int) //管理学院 ref teacher, college
    '''
    teacher_id=models.ForeignKey(teacher,on_delete=models.CASCADE)
    college_id=models.ForeignKey(college,on_delete=models.CASCADE)
    class Meta:
        unique_together = ("teacher_id","college_id")
    primary = ("teacher_id","college_id")


class assist(models.Model):
    '''
    assist(student_id int, course_id int) //助教 ref student, course
    '''

    student_id = models.ForeignKey(student, on_delete=models.CASCADE)
    course_id = models.ForeignKey(course, on_delete=models.CASCADE)
    class Meta:
        unique_together = ("student_id", "course_id")
    primary = ("student_id", "course_id")


class admin(models.Model):
    '''
    admin(admin_id int, name varchar(20) not null) //系统管理员
    '''
    admin_id=models.CharField(max_length=20,primary_key=True)
    name=models.CharField(max_length=20,null=False)


class operation(models.Model):
    '''
    operation(operation_id int, description text not null) //表操作 const
    '''

courseSelect/models.py
from django.db import models
from basicInfo.models import student as Student, teacher as Teacher, course as Course, discipline as Discipline, takeup as Takeup, teach as Teach
# Create your models here.

# 选课信息
class Selection(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE) # ref Student, 学生
    teach = models.ForeignKey(Teach, on_delete=models.CASCADE) # ref Teach, 排课信息
    select_time = models.DateTimeField(null=True) # 选课时间
    priority = models.IntegerField() # 优先级
    state = models.BooleanField() # 选课状态，即是否选上

# 培养方案
class Curriculum(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE) # ref Student, 学生
    courses = models.ManyToManyField(Course, related_name='course_curriculum', null=True) # ref Course, 课程
   
class RequiredCourse(models.Model):
    discipline = models.ForeignKey(Discipline, on_delete=models.CASCADE)
    required_courses = models.ManyToManyField(Course, related_name='required_course', null=True)

class CreditNeed(models.Model):
    discipline = models.ForeignKey(Discipline, on_delete=models.CASCADE, unique=True) # ref Major, 专业
    elective = models.FloatField() # 选修课最低学分要求
    public = models.FloatField() # 公共课最低学分要求

class TimeSlot(models.Model):
    start = models.DateTimeField(null=False)
    end = models.DateTimeField(null=False)

class SelectControl(models.Model):
    first_time = models.ForeignKey(TimeSlot, related_name='first_time', on_delete=models.CASCADE)
    apply_time = models.ForeignKey(TimeSlot, related_name='apply_time', on_delete=models.CASCADE)
    withdraw_time = models.ForeignKey(TimeSlot, on_delete=models.CASCADE)
    max_connections = models.IntegerField(default=500)

courseSelect/templates/courseSelect/_left.html
<div class="header-section no-print">
    <!-- top_bg -->
    <div class="top_bg">			
        <div class="header_top">
            <div class="top_right">
                <ul>
                    <li><a href="#">浙江大学教务中心</a></li>|
                    <li>{% if account.type == 0 %}
                            <a href="/basic/student">首页</a>
                            {% elif account.type == 1 %}
                            <a href="/basic/teacher_index">首页</a>
                            {% elif account.type == 2 %} 
                            <a href="/basic/admin_index">首页</a>
                            {% endif %}</li>|
                </ul>
            </div>
            <div class="top_left">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" style="color:white">
                        <i class="fa fa-user fa-fw"></i> <i id="account_id" class="fa fa-caret-down">&nbsp;&nbsp;{{ account.account_id }}</i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="/basic/login"><i class="fa fa-sign-out fa-fw"></i>登出</a></li>
                        <li><a href="/basic/teacher_index"><i class="fa fa-cog fa-fw"></i>设置</a></li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
            </div>
            <div class="clearfix"> </div>
        </div>
        <div class="clearfix"></div>
    </div>
    {% if account.type == 0 %}
    {% include 'basicInfo/student_menu.html' %}
    {% elif account.type == 1 %}
    {% include 'basicInfo/teacher_menu.html' %}
    {% elif account.type == 2 %}
    {% include 'basicInfo/admin_menu.html' %}
    {% endif %}
    <!-- <div class="sidebar-menu">
        <header class="logo1">
            <a href="#" class="sidebar-icon">
                <span class="fa fa-bars"></span>
            </a>
        </header>
        <div style="border-top:1px ridge rgba(255, 255, 255, 0.15)"></div>
        <div class="menu">
            <ul id="menu">
                <li>
                    <a href="index.html">
                        <i class="fa fa-tachometer"></i>
                        <span>主页</span>
                    </a>
                </li>
                <li id="menu-academico">
                    <a href="#">
                        <i class="fa fa-table"></i>
                        <span> 选课</span>
                        <span class="fa fa-angle-right" style="float: right"></span>
                    </a>
                    <ul id="menu-academico-sub">
                        <li id="menu-academico-avaliacoes">
                            <a href="{% url 'courses' %}">课程搜索</a>
                        </li>
                        <li id="menu-academico-avaliacoes">
                            <a href="{% url 'table' %}">我的课表</a>
                        </li>
                        <li id="menu-academico-avaliacoes">
                            <a href="{% url 'course_select' %}">选课</a>
                        </li>
                        <li id="menu-academico-avaliacoes">
                            <a href="{% url 'curriculum' %}">培养方案</a>
                        </li>
                        <li id="menu-academico-boletim">
                            <a href="{% url 'teacher' %}">教师导出</a>
                        </li>
                        <li id="menu-academico-boletim">
                            <a href="{% url 'control' %}">管理平台</a>
                        </li>
                        <li id="menu-academico-boletim">
                            <a href="{% url 'import' %}">手动导入</a>
                        </li>
                    </ul>
                </li>
                <li id="menu-academico">
                    <a href="sunglasses.html">
                        <i class="fa fa-file-text-o"></i>
                        <span>论坛</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'table' %}">
                        <i class="lnr lnr-pencil"></i>
                        <span>我的课表</span>
                    </a>
                </li>
                {% comment %} <li id="menu-academico">
                    <a href="catalog.html">
                        <i class="fa fa-file-text-o"></i>
                        <span>Catalog</span>
                    </a>
                </li>
                <li id="menu-academico">
                    <a href="{% url 'course_select' %}">
                        <i class="lnr lnr-book"></i>
                        <span>选课</span>
                    </a>
                </li>
                <li>
                    <a href="bags.html">
                        <i class="lnr lnr-envelope"></i>
                        <span>Bags</span>
                    </a>
                </li>
                <li>
                    <a href="products.html">
                        <i class="lnr lnr-chart-bars"></i>
                        <span>Watches</span>
                    </a>
                </li>
                <li id="menu-academico">
                    <a href="#">
                        <i class="lnr lnr-layers"></i>
                        <span>Tabs & Calender</span>
                        <span class="fa fa-angle-right" style="float: right"></span>
                    </a>
                    <ul id="menu-academico-sub">
                        <li id="menu-academico-avaliacoes">
                            <a href="tabs.html">Tabs</a>
                        </li>
                        <li id="menu-academico-boletim">
                            <a href="calender.html">Calender</a>
                        </li>

                    </ul>
                </li>
                <li>
                    <a href="#">
                        <i class="lnr lnr-chart-bars"></i>
                        <span>Forms</span>
                        <span class="fa fa-angle-right" style="float: right"></span>
                    </a>
                    <ul>
                        <li>
                            <a href="input.html"> Input</a>
                        </li>
                        <li>
                            <a href="validation.html">Validation</a>
                        </li>
                    </ul>
                </li> {% endcomment %}
            </ul>
        </div>
    </div> -->
    <!-- /top_bg -->
</div>
<script>
    var toggle = true;

    $(".sidebar-icon").click(function() {
        if (toggle) {
            $(".page-container").addClass("sidebar-collapsed").removeClass("sidebar-collapsed-back");
            $("#menu span").css({
                "position": "absolute"
            });
        } else {
            $(".page-container").removeClass("sidebar-collapsed").addClass("sidebar-collapsed-back");
            setTimeout(function() {
                $("#menu span").css({
                    "position": "relative"
                });
            }, 400);
        }

        toggle = !toggle;
    });
</script>

courseSelect/templates/courseSelect/courses.html
{% extends 'courseSelect/base.html' %}
{% load course_select_tags %}
{% load pagination_tags %}
{% block content %}

{% include 'courseSelect/_left.html' %}
<div class="header_bg">
    <div class="header">
        <div class="head-t">
            <div style="display: inline-block; font-size: 0.875rem">
                欢迎！<br/>
                本界面仅提供课程搜索，选课请进入选课界面！
            </div>
            <!-- start header_right -->
            {% include 'courseSelect/_search.html' %}

        </div>
    </div>
</div>

<div class="content">
    <div class="monthly-grid">
        <div class="panel panel-widget">
            <div class="panel-title">
                课程列表
                <div class="clearfix"> </div>
                <div id="app_table">
                    <template>
                        <el-table stripe :data="tableData" :row-key="getRowKeys" :expand-row-keys="expands"  @expand-change="toggleRowExpansion" style="width: 100%">
                            <el-table-column prop="course_id" label="课程代码">
                            </el-table-column>
                            <el-table-column label="课程名称">
                                <template slot-scope="scope">
                                    <el-button type="text" @click="scope.row.dialogVisible = true"> [[ scope.row.course_name]] </el-button>
                                    <el-dialog
                                        title="课程详细内容"
                                        :visible.sync="scope.row.dialogVisible"
                                        :modal-append-to-body="false"
                                        :append-to-body="true"
                                        width="40%">
                                        <dl class="dl-horizontal">
                                            <dt>课程名称</dt> <dd>[[ scope.row.course_name ]]</dd>
                                            <dt>课程代码</dt> <dd>[[ scope.row.course_id ]]</dd>
                                            <dt>课程类别</dt> <dd>[[ scope.row.course_type ]]</dd>
                                            <dt>学分</dt> <dd>[[ scope.row.course_credit ]]</dd>
                                            <dt>周学时</dt> <dd>[[ scope.row.course_hours ]]</dd>
                                            <dt>简介</dt> <dd>[[ scope.row.intro ]]</dd>
                                        </dl>
                                        <span slot="footer" class="dialog-footer">
                                        <el-button @click="scope.row.dialogVisible = false">关 闭</el-button>
                                        </span>
                                    </el-dialog>
                                </template>
                            </el-table-column>
                            <el-table-column prop="course_type" label="课程类别">
                            </el-table-column>
                            <el-table-column prop="course_credit" label="学分">
                            </el-table-column>
                            <el-table-column prop="course_hours" label="学时">
                            </el-table-column>
                            <el-table-column fixed="right" label="操作" type="expand">
                                <template slot-scope="scope">
                                    <el-table :data="sectionData(scope.row)" style="width: 100%" >
                                        <el-table-column prop="id" label="序号"></el-table-column>
                                        <el-table-column prop="teacher" label="授课教师"></el-table-column>
                                        <el-table-column prop="room" label="上课地点"></el-table-column>
                                        <el-table-column prop="capacity" label="容量"></el-table-column>
                                        <el-table-column prop="time" label="上课时间" width="350"></el-table-column>
                                        <el-table-column fixed="right" label="操作">
                                            <template slot-scope="tem" >
                                                <el-button size="mini" disabled>选课</el-button>
                                                
                                            </template>
                                        </el-table-column>
                                    </el-table>
                                </template>
                            </el-table-column>
                            
                        </el-table>
                    </template>
                    <br>
                    
                    {% autopaginate courses 10 %}
                    {% paginate using "courseSelect/_paginate.html" %}
                </div>
            </div>
        </div>
    </div>

    <div class="clearfix"> </div>
</div>
<div class="clearfix"></div>
<script>
    distinct = (arr_str) => {
        arr = arr_str.split(',');
        var temp = {}, r = [], len = arr.length, val, type;
        for (var i = 0; i < len; i++) {
            val = arr[i];
            type = typeof val;
            if (!temp[val]) {
                temp[val] = [type];
                r.push(val);
            } else if (temp[val].indexOf(type) < 0) {
                temp[val].push(type);
                r.push(val);
            }
        }
        return r.join('\n');
    }
    display_weekday = (num) =>{
        switch(num){
            case '1':return '一  ';
            case '2':return '二  ';
            case '3':return '三  ';
            case '4':return '四  ';
            case '5':return '五  ';
            case '6':return '六  ';
            case '7':return '日  ';
        }
    }
    //getting CSRF token
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }            
    var csrftoken = getCookie('csrftoken');

    new Vue({
        delimiters:['[[', ']]'],
        el: "#app_table",
        methods: {
            toggleRowExpansion(row,expandedRows){
                this.expands = [];
                expandedRows.forEach((element)=>{
                    this.expands.push(element['course_id']);
                })
                console.log(this.expands);
                $.cookie('expands', this.expands.join(','));
            },
            sectionData(row) {
                return row['section'];

            },
            
            
        },

        data() {
            return {
                tableData: [
                
                {% for course in courses %}{% if course.type != '0' %}
                    { 
                        course_id: "{{ course.course_id }}",
                        course_name: "{{ course.name }}",
                        course_type: "{{ course.get_type_display }}",
                        course_credit: "{{ course.credit }}",
                        course_hours: "{{ course.hour }}",//???
                        intro: "{{ course.intro  }}",
                        dialogVisible: false,
                        section: [
                            {% getSectionByCourse course.course_id as sections%}
                            {% for sec in sections %}
                            {
                                section_id: "{{sec.teach_id}}",
                                id: "{{forloop.counter}}",
                                teacher: 
                                    {% getTeacherBySection sec.teach_id as teacher %}
                                    "{{teacher.name}}"
                                ,
                                room: 
                                    {% getRoomBySection sec.teach_id as rooms %}
                                    "{% for room in rooms %}{{room.location}}{%if forloop.revcounter0 == 0%}{%else%},{%endif%}{% endfor %}"
                                ,
                                time: 
                                    {% getTimeBySection sec.teach_id as time_ %}
                                    distinct("{% for time in time_ %}{% if time.day %}周" +display_weekday("{{time.day}}") +"{{time.start}} - {{time.end}}{%if forloop.revcounter0 == 0%}{%else%},{%endif%}{%endif%}{% endfor %}")
                                ,
                                capacity:
                                    "{% getCapacityBySection sec.teach_id %}",
                            },
                            {% endfor %}
                        ]
                    },{% endif %}
                {% endfor %}
                ],
                getRowKeys(row) {
                    return row['course_id'];
                },
                expands: []
            }
        },
        mounted() {
            // 在这里你想初始化的时候展开哪一行都可以了
            
            //
            this.expands=$.cookie('expands').split(',');
            
        }
    })
</script>
<style>
    .course-detail{
        text-indent:5em;
    }

</style>

{% endblock content %}