forum/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.home, name='forum'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/list/$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
    url(r'^post/search/$', views.post_search, name='post_search'),
    url(r'^reply/new/(?P<pk>[0-9]+)/$', views.reply_new, name='reply_edit'),
    url(r'^bulletin/new/$', views.bulletin_new, name='bulletin_new'),
    url(r'^message/new/$', views.message_new, name='message_new'),
    url(r'^message/send$', views.message_send, name='message_send'),
    url(r'^message/receive/$', views.message_receive, name='message_receive'),
    url(r'^upload/(?P<pk>[0-9]+)/$', views.upload, name='upload'),
    url(r'^download/(?P<pk>[0-9]+)/$', views.file_down, name='download'),
]

jwsystem/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'jwsystem.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    
    url(r'^admin/', include(admin.site.urls)),
    url(r'^course_select/', include('courseSelect.urls')),
    url(r"^basic/",include('basicInfo.urls')),
    url(r"^api/",include('basicInfo.apiUrls')),
    url(r'^forum/', include('forum.urls')),
    url(r'^course_arrange/', include('courseArrange.urls')),
    url(r'^online_test/', include('onlineTest.urls', namespace='online_test'))
]

onlineTest/urls.py
from django.conf.urls import url

from . import views

app_name = 'online_test'
urlpatterns = [
    url('subjects/student', views.SubjectsStudentView.as_view(), name='subjects_student'),
    url('subjects/teacher', views.SubjectsTeacherView.as_view(), name='subjects_teacher'),
    url('subject/(?P<subject>[0-9a-zA-Z]+)/tests', views.TestsView.as_view(), name='tests'),
    url('test/(?P<pk>[0-9]+)/', views.TestDetail.as_view(), name='test_detail'),
    url('test/submit_answer/', views.submit_answer, name='judge'),
    url('subject/(?P<subject>[0-9a-zA-Z]+)/statistics/teacher/tests', views.TeacherStatisticsTests.as_view(),
        name='teacher_statistics_tests'),
    url('subject/(?P<subject>[0-9a-zA-Z]+)/statistics/teacher/chapters', views.TeacherStatisticsChapters.as_view(),
        name='teacher_statistics_chapters'),
    url('subject/(?P<subject>[0-9a-zA-Z]+)/statistics/teacher/knowledge_points',
        views.TeacherStatisticsKnowledgePoints.as_view(), name='teacher_statistics_knowledge_points'),
    url('subject/(?P<subject>[0-9a-zA-Z]+)/statistics/student/', views.StudentStatistics.as_view(),
        name='student_statistics'),
    url('test_statistics/(?P<pk>[0-9]+)/', views.TestStatistics.as_view(), name='test_statistics'),
    url('test_statistics/student/(?P<pk>[0-9]+)/(?P<student_pk>[0-9a-zA-Z]+)/',
        views.TestStatisticsStudentRecord.as_view(), name='test_statistics_student_record'),
    url('test_statistics/teacher/(?P<pk>[0-9]+)/(?P<student_pk>[0-9a-zA-Z]+)/',
        views.TestStatisticsTeacherRecord.as_view(), name='test_statistics_teacher_record'),

    url('problem_bank/single_problem/choice/(?P<pk>[0-9a-zA-Z]+)/', views.SingleChoice.as_view(), name='problem_choice'),
    url('problem_bank/single_problem/judge/(?P<pk>[0-9a-zA-Z]+)/', views.SingleJudge.as_view(), name='problem_judge'),
    url('problem_bank/single_problem/static/choice/(?P<pk>[0-9a-zA-Z]+)/', views.SingleStaticChoice.as_view(),
        name='static_choice'),
    url('problem_bank/single_problem/static/judge/(?P<pk>[0-9a-zA-Z]+)/', views.SingleStaticJudge.as_view(),
        name='static_judge'),
    url('problem_bank/single_problem', views.SingleProblem.as_view(), name='problem_single'),
    url('problem_bank/search/', views.problem_search, name="problem_search"),
    url('problem_bank/add/', views.problem_add, name="problem_add"),
    url('problem_bank/(?P<pk>[0-9a-zA-Z]+)/mod/', views.problem_mod, name="problem_mod"),
    url('problem_bank/(?P<pk>[0-9a-zA-Z]+)/del/', views.problem_del, name="problem_del"),
    url('problem_bank/detail/', views.ProblemDetail.as_view(), name="problem_detail"),

    url('problem_bank/subject', views.subject, name='subject'),
    url('problem_bank/chapter', views.chapter, name='chapter'),
    url('problem_bank/knowledge_point', views.knowledge_point, name='knowledge_point'),

    url('problem_bank/', views.ProblemBank.as_view(), name='problem_bank'),

    url('teacher/test/auto-generation/(?P<pk>[0-9a-zA-Z]+)/del/', views.test_del, name="test_del"),
    url('teacher/test/auto-generation/(?P<pk>[0-9a-zA-Z]+)/mod/', views.test_mod, name="test_mod"),
    url('teacher/test/auto-generation/add/', views.test_add, name="test_add"),
    url('teacher/test/auto-generation/gerner/', views.test_gerner, name="test_gerner"),
    url('teacher/test/auto-generation/search/', views.test_search, name="test_search"),
    url('teacher/test/auto-generation', views.AutoTestGeneration.as_view(), name='auto_test_generation'),

]

onlineTest/views.py
from django.http import HttpRequest, HttpResponse
from django.utils import timezone
from django.views import generic
import json
import datetime
from .models import Test, ChoiceQuestionAnswerRecord, ChoiceQuestion, TrueOrFalseQuestionAnswerRecord, \
    TrueOrFalseQuestion, Chapter, KnowledgePoint

from basicInfo.models import course as Subject, teach as Teach, student as Student, teacher as Teacher, \
    account as Account
from courseSelect.models import Selection


# login_student = Student.objects.all()[0]
# login_student = None
# # login_teacher = Teacher.objects.all()[0]
# login_teacher = None


class SubjectsTeacherView(generic.ListView):
    model = Subject
    template_name = 'online_test/subjects_teacher.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        # object_list = login_teacher.subjects.all()
        account_id = self.request.session['account_id']
        account = Account.objects.get(account_id=account_id)
        context['account'] = account

        login_teacher = Teacher.objects.get(teacher_id=account_id)

        object_list = []
        for teach in Teach.objects.filter(teacher_id=login_teacher):
            object_list.append(teach.course_id)
        context['object_list'] = object_list

        return context


class SubjectsStudentView(generic.ListView):
    model = Subject
    template_name = 'online_test/subjects_student.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        # object_list = login_student.subjects.all()
        account_id = self.request.session['account_id']
        account = Account.objects.get(account_id=account_id)
        context['account'] = account
        login_student = Student.objects.get(student_id=account_id)

        object_list = []
        for teach in Selection.objects.filter(student=login_student, state=True):
            object_list.append(teach.teach.course_id)
        context['object_list'] = object_list
        return context


class TestsView(generic.ListView):
    model = Test
    template_name = 'online_test/tests.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        subject = Subject.objects.get(course_id=self.kwargs['subject'])

        context = super().get_context_data(**kwargs)

        account_id = self.request.session['account_id']
        account = Account.objects.get(account_id=account_id)
        context['account'] = account
        login_student = Student.objects.get(student_id=account_id)

        object_list = Test.objects.filter(attend_students=login_student, subject=subject)
        context['object_list'] = object_list
        context['subject_id'] = subject.course_id
        return context


class TestDetail(generic.DetailView):
    model = Test
    template_name = 'online_test/test_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        account_id = self.request.session['account_id']
        account = Account.objects.get(account_id=account_id)
        context['account'] = account
        login_student = Student.objects.get(student_id=account_id)

        context['choice_question_answer_record'] = {}
        for record in ChoiceQuestionAnswerRecord.objects.filter(test=self.object, student=login_student):
            context['choice_question_answer_record'][record.question.id] = record.answer
            print(record.answer, record.id, record.question)

        context['true_or_false_question_answer_record'] = {}
        for record in TrueOrFalseQuestionAnswerRecord.objects.filter(test=self.object, student=login_student):
            # context['true_or_false_question_answer_record'][record.id] = 'T' if record.answer else 'F'
            print(record.answer, record.id, record.question)

            if record.answer == True:
                context['true_or_false_question_answer_record'][record.question.id] = 'T'
            elif record.answer == False:
                context['true_or_false_question_answer_record'][record.question.id] = 'F'
            else:
                context['true_or_false_question_answer_record'][record.question.id] = 'None'

        return context


class TeacherStatisticsTests(generic.ListView):
    model = Test
    template_name = 'online_test/teacher_statistics_tests.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        subject = Subject.objects.get(course_id=self.kwargs['subject'])
        context = super().get_context_data(**kwargs)

        account_id = self.request.session['account_id']
        account = Account.objects.get(account_id=account_id)
        context['account'] = account
        login_teacher = Teacher.objects.get(teacher_id=account_id)

        object_list = Test.objects.filter(creator=login_teacher, subject=subject)
        context['object_list'] = object_list
        context['subject_id'] = subject.course_id

        return context


class TeacherStatisticsChapters(generic.ListView):
    model = Chapter
    template_name = 'online_test/teacher_statistics_chapters.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        account_id = self.request.session['account_id']
        account = Account.objects.get(account_id=account_id)
        context['account'] = account
        login_teacher = Teacher.objects.get(teacher_id=account_id)

        subject = Subject.objects.get(course_id=self.kwargs['subject'])

        object_list = {}
        for test in Test.objects.filter(creator=login_teacher, subject=subject):
            for record in ChoiceQuestionAnswerRecord.objects.filter(test=test):
                if record.question.chapter not in object_list.keys():
                    object_list[record.question.chapter] = {'correct_num': 0, 'total_num': 1}
                    if record.answer == record.question.solution:
                        object_list[record.question.chapter]['correct_num'] += 1
                else:
                    object_list[record.question.chapter]['total_num'] += 1
                    if record.answer == record.question.solution:
                        object_list[record.question.chapter]['correct_num'] += 1

            for record in TrueOrFalseQuestionAnswerRecord.objects.filter(test=test):
                if record.question.chapter not in object_list.keys():
                    object_list[record.question.chapter] = {'correct_num': 0, 'total_num': 1}
                    if record.answer == record.question.solution:
                        object_list[record.question.chapter]['correct_num'] += 1
                else:
                    object_list[record.question.chapter]['total_num'] += 1
                    if record.answer == record.question.solution:
                        object_list[record.question.chapter]['correct_num'] += 1
        context['object_list'] = object_list
        context['subject_id'] = subject.course_id

        return context


class TeacherStatisticsKnowledgePoints(generic.ListView):
    model = KnowledgePoint
    template_name = 'online_test/teacher_statistics_knowledge_points.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        account_id = self.request.session['account_id']
        account = Account.objects.get(account_id=account_id)
        context['account'] = account
        login_teacher = Teacher.objects.get(teacher_id=account_id)

        subject = Subject.objects.get(course_id=self.kwargs['subject'])

        object_list = {}
        for test in Test.objects.filter(creator=login_teacher, subject=subject):
            print(test)
            for record in ChoiceQuestionAnswerRecord.objects.filter(test=test):
                if record.question.knowledge_point not in object_list.keys():
                    object_list[record.question.knowledge_point] = {'correct_num': 0, 'total_num': 1}
                    if record.answer == record.question.solution:
                        object_list[record.question.knowledge_point]['correct_num'] += 1
                else:
                    object_list[record.question.knowledge_point]['total_num'] += 1
                    if record.answer == record.question.solution:
                        object_list[record.question.knowledge_point]['correct_num'] += 1

            for record in TrueOrFalseQuestionAnswerRecord.objects.filter(test=test):
                if record.question.knowledge_point not in object_list.keys():
                    object_list[record.question.knowledge_point] = {'correct_num': 0, 'total_num': 1}
                    if record.answer == record.question.solution:
                        object_list[record.question.knowledge_point]['correct_num'] += 1
                else:
                    object_list[record.question.knowledge_point]['total_num'] += 1
                    if record.answer == record.question.solution:
                        object_list[record.question.knowledge_point]['correct_num'] += 1
        context['object_list'] = object_list
        context['subject_id'] = subject.course_id

        return context


class TestStatistics(generic.DetailView):
    model = Test
    template_name = 'online_test/test_statistics.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        test_score = 0

        account_id = self.request.session['account_id']
        account = Account.objects.get(account_id=account_id)
        context['account'] = account

        assert isinstance(self.object, Test)

        for question in self.object.choice_questions.all():
            test_score += question.score

        for question in self.object.true_or_false_questions.all():
            test_score += question.score

        avg_score = 0
        student_scores = []

onlineTest/templates/online_test/teacher_statistics_chapters.html
{% load static %}
<!DOCTYPE HTML>
<html>

<head>
    <title>浙江大学教务中心</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content="Gretong Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design"/>
    <script type="application/x-javascript"> addEventListener("load", function () {
        setTimeout(hideURLbar, 0);
    }, false);

    function hideURLbar() {
        window.scrollTo(0, 1);
    } </script>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'online_test/css/bootstrap.min.css' %}" rel='stylesheet' type='text/css'/>
    <!-- Custom CSS -->
    <link href="{% static 'online_test/css/style.css' %}" rel='stylesheet' type='text/css'/>
    <!-- Graph CSS -->
    <link href="{% static 'online_test/css/font-awesome.css' %}" rel="stylesheet">
    <!-- jQuery -->
    <link href='https://fonts.googleapis.com/css?family=Roboto:700,500,300,100italic,100,400' rel='stylesheet'
          type='text/css'/>
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <!-- lined-icons -->
    <link rel="stylesheet" href="{% static 'online_test/css/icon-font.min.css' %}" type='text/css'/>
    <script src="{% static 'online_test/js/simpleCart.min.js' %}"></script>
    <script src="{% static 'online_test/js/amcharts.js' %}"></script>
    <script src="{% static 'online_test/js/serial.js' %}"></script>
    <script src="{% static 'online_test/js/light.js' %}"></script>
    <!-- //lined-icons -->
    <script src="{% static 'online_test/js/jquery-1.10.2.min.js' %}"></script>
    <!-- <script src="{% static 'online_test/js/test_detail.js' %}"></script> -->

</head>

<body>
<div class="left-content">
    <div class="inner-content">
        <div class="header-section">
            <!-- top_bg -->
            <div class="top_bg">
                <div class="header_top">
                    <div class="top_right">
                        <ul>
                            <li>
                                <a href="#">浙江大学教务中心</a>
                            </li>-
                            <li>
                                <a href="/basic/teacher">首页</a>
                            </li>-
                            <li>
                                <a href="/online_test/subjects/teacher">在线测试</a>
                            </li>
                        </ul>
                    </div>
                    <div class="top_left">
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#" style="color:white">
                                <i class="fa fa-user fa-fw"></i>
                                <i id="account_id" class="fa fa-caret-down">&nbsp;&nbsp;{{ account.account_id }}</i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li>
                                    <a href="/basic/login">
                                        <i class="fa fa-sign-out fa-fw"></i>登出</a>
                                </li>
                                <li>
                                    <a href="/basic/teacher_index">
                                        <i class="fa fa-cog fa-fw"></i>设置</a>
                                </li>
                            </ul>
                            <!-- /.dropdown-user -->
                        </li>
                    </div>
                    <div class="clearfix"> </div>
                </div>
                <div class="clearfix"></div>
            </div>
            {% if account.type == 0 %} {% include 'basicInfo/student_menu.html' %} {% elif account.type == 1 %} {% include 'basicInfo/teacher_menu.html'%}
            {% elif account.type == 2 %} {% include 'basicInfo/admin_menu.html' %} {% endif %}
            <!-- //header-ends -->
            <div class="clearfix"></div>
        </div>



        <div class="content">
            <div class="women_main">
                <table class="table">
                    <thead>
                    <tr>
                        <th>
                            章节
                        </th>
                        <th>
                            总成绩
                        </th>
                        <th>
                            总分
                        </th>
                    </tr>
                    </thead>
                    {% if object_list.items %}
                        {% for chapter, info in object_list.items %}
                            <tr>
                                <td width="50%">
                                    {{ chapter.chapter }}
                                </td>
                                <td>
                                    {{ info.correct_num }}
                                </td>
                                <td>
                                    {{ info.total_num }}
                                </td>
                            </tr>
                        {% endfor %}
                    {% endif %}
                </table>


            </div>
        </div>
    </div>
</div>

<div class="sidebar-menu">
	<header class="logo1">
		<a href="#" class="sidebar-icon"> <span class="fa fa-bars"></span> </a>
	</header>
	<div style="border-top:1px ridge rgba(255, 255, 255, 0.15)"></div>
    <div class="menu">
		<ul id="menu" >
			<li><a href="/basic/teacher_information"><i class="lnr lnr-pencil"></i> <span>个人信息</span></a></li>
			<!-- <li><a href="/basic/teacher_comment"><i class="fa fa-file-text-o"></i> <span>学生评价</span></a></li> -->
			<li id="menu-academico" ><a href="#"><i class="fa fa-table"></i> <span> 课程信息</span> <span class="fa fa-angle-right" style="float: right"></span></a>
				<ul id="menu-academico-sub" >
					<li><a href="{% url 'courses' %}">课程搜索</a></li>
					<li id="menu-academico-avaliacoes" ><a href="/basic/teacher_course_regist">申请开课</a></li>
					<li id="menu-academico-avaliacoes" ><a href="/basic/teacher_course_open">申请开班</a></li>
					<li><a href="{% url 'teacher' %}">教师导出</a></li>
				</ul>
			</li>
			<li><a href="{% url 'calender' %}"><i class="fa fa-file-text-o"></i><span>课表安排</span></a></a></li>
			<li><a href="{% url 'forum' %}"><i class="lnr lnr-envelope"></i> <span>浙大论坛</span></a></li>
			<li id="menu-academico" ><a href="#"><i class="lnr lnr-layers"></i> <span> 在线测试</span> <span class="fa fa-angle-right" style="float: right"></span></a>
                <ul id="menu-academico-sub" >
                    <li><a href="{% url 'online_test:subjects_teacher' %}">重选课程</a></li>
                    <a href="{% url 'online_test:teacher_statistics_tests' subject_id %}"> 重选题库 </a>
                    <li><a href="{% url 'online_test:teacher_statistics_chapters' subject_id %}">章节统计</a></li>
                    <li><a href="{% url 'online_test:teacher_statistics_knowledge_points' subject_id %}"> 知识点统计 </a></li>
                    <li><a href="{% url 'online_test:problem_bank' %}">题库管理</a></li>
                    <li><a href="{% url 'online_test:auto_test_generation' %}">试卷管理</a></li>

				</ul>
            </li>
		</ul>
	</div>
	<div class="clearfix"></div>
</div>


<!--js -->
<script src="{% static 'online_test/js/jquery.nicescroll.js' %}"></script>
<script src="{% static 'online_test/js/scripts.js' %}"></script>
<!-- Bootstrap Core JavaScript -->
<script src="{% static 'online_test/js/bootstrap.min.js' %}"></script>
<!-- /Bootstrap Core JavaScript -->
<!-- real-time -->


<script src="{% static 'online_test/js/menu_jquery.js' %}"></script>
</body>

</html>

onlineTest/templates/online_test/teacher_statistics_tests.html
{% load static %}
<!DOCTYPE HTML>
<html>

<head>
    <title>浙江大学教务中心</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content="Gretong Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design"/>
    <script type="application/x-javascript"> addEventListener("load", function () {
        setTimeout(hideURLbar, 0);
    }, false);

    function hideURLbar() {
        window.scrollTo(0, 1);
    } </script>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'online_test/css/bootstrap.min.css' %}" rel='stylesheet' type='text/css'/>
    <!-- Custom CSS -->
    <link href="{% static 'online_test/css/style.css' %}" rel='stylesheet' type='text/css'/>
    <!-- Graph CSS -->
    <link href="{% static 'online_test/css/font-awesome.css' %}" rel="stylesheet">
    <!-- jQuery -->
    <link href='https://fonts.googleapis.com/css?family=Roboto:700,500,300,100italic,100,400' rel='stylesheet'
          type='text/css'/>
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <!-- lined-icons -->
    <link rel="stylesheet" href="{% static 'online_test/css/icon-font.min.css' %}" type='text/css'/>
    <script src="{% static 'online_test/js/simpleCart.min.js' %}"></script>
    <script src="{% static 'online_test/js/amcharts.js' %}"></script>
    <script src="{% static 'online_test/js/serial.js' %}"></script>
    <script src="{% static 'online_test/js/light.js' %}"></script>
    <!-- //lined-icons -->
    <script src="{% static 'online_test/js/jquery-1.10.2.min.js' %}"></script>
    <!-- <script src="{% static 'online_test/js/test_detail.js' %}"></script> -->

</head>

<body>
<div class="left-content">
    <div class="inner-content">
        <div class="header-section">
            <!-- top_bg -->
            <div class="top_bg">
                <div class="header_top">
                    <div class="top_right">
                        <ul>
                            <li>
                                <a href="#">浙江大学教务中心</a>
                            </li>-
                            <li>
                                <a href="/basic/teacher">首页</a>
                            </li>-
                            <li>
                                <a href="/online_test/subjects/teacher">在线测试</a>
                            </li>
                        </ul>
                    </div>
                    <div class="top_left">
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#" style="color:white">
                                <i class="fa fa-user fa-fw"></i>
                                <i id="account_id" class="fa fa-caret-down">&nbsp;&nbsp;{{ account.account_id }}</i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li>
                                    <a href="/basic/login">
                                        <i class="fa fa-sign-out fa-fw"></i>登出</a>
                                </li>
                                <li>
                                    <a href="/basic/teacher_index">
                                        <i class="fa fa-cog fa-fw"></i>设置</a>
                                </li>
                            </ul>
                            <!-- /.dropdown-user -->
                        </li>
                    </div>
                    <div class="clearfix"> </div>
                </div>
                <div class="clearfix"></div>
            </div>
            {% if account.type == 0 %} {% include 'basicInfo/student_menu.html' %} {% elif account.type == 1 %} {% include 'basicInfo/teacher_menu.html'%}
            {% elif account.type == 2 %} {% include 'basicInfo/admin_menu.html' %} {% endif %}
            <!-- //header-ends -->
            <div class="clearfix"></div>
        </div>


        <div class="content">
            <div class="women_main">
                <table class="table">
                    <thead>
                        <tr>
                            <th width="400px">
                                标题
                            </th>
                            <th>
                                创建者
                            </th>
                            <th>
                                开始时间
                            </th>
                            <th>
                                结束时间
                            </th>
                        </tr>
                    </thead>
                    {% if object_list %}
                        {% for test in object_list %}
                        <tr>
                            <td width="50%">
                                <a href="{% url 'online_test:test_statistics' test.id %}">{{ test.name }}</a>
                            </td>
                            <td width="10%">
                                {{ test.creator }}
                            </td>
                            <td>
                                {{ test.start_time }}
                            </td>
                            <td>
                                {{ test.end_time }}
                            </td>
                        </tr>
                        {% endfor %}
                    {% endif %}
                </table>
            </div>
        </div>
    </div>
</div>

<div class="sidebar-menu">
	<header class="logo1">
		<a href="#" class="sidebar-icon"> <span class="fa fa-bars"></span> </a>
	</header>
	<div style="border-top:1px ridge rgba(255, 255, 255, 0.15)"></div>
    <div class="menu">
		<ul id="menu" >
			<li><a href="/basic/teacher_information"><i class="lnr lnr-pencil"></i> <span>个人信息</span></a></li>
			<!-- <li><a href="/basic/teacher_comment"><i class="fa fa-file-text-o"></i> <span>学生评价</span></a></li> -->
			<li id="menu-academico" ><a href="#"><i class="fa fa-table"></i> <span> 课程信息</span> <span class="fa fa-angle-right" style="float: right"></span></a>
				<ul id="menu-academico-sub" >
					<li><a href="{% url 'courses' %}">课程搜索</a></li>
					<li id="menu-academico-avaliacoes" ><a href="/basic/teacher_course_regist">申请开课</a></li>
					<li id="menu-academico-avaliacoes" ><a href="/basic/teacher_course_open">申请开班</a></li>
					<li><a href="{% url 'teacher' %}">教师导出</a></li>
				</ul>
			</li>
			<li><a href="{% url 'calender' %}"><i class="fa fa-file-text-o"></i><span>课表安排</span></a></a></li>
			<li><a href="{% url 'forum' %}"><i class="lnr lnr-envelope"></i> <span>浙大论坛</span></a></li>
			<li id="menu-academico" ><a href="#"><i class="lnr lnr-layers"></i> <span> 在线测试</span> <span class="fa fa-angle-right" style="float: right"></span></a>
                <ul id="menu-academico-sub" >
                    <li><a href="{% url 'online_test:subjects_teacher' %}">重选课程</a></li>
                    <a href="{% url 'online_test:teacher_statistics_tests' subject_id %}"> 重选题库 </a>
                    <li><a href="{% url 'online_test:teacher_statistics_chapters' subject_id %}">章节统计</a></li>
                    <li><a href="{% url 'online_test:teacher_statistics_knowledge_points' subject_id %}"> 知识点统计 </a></li>
                    <li><a href="{% url 'online_test:problem_bank' %}">题库管理</a></li>
                    <li><a href="{% url 'online_test:auto_test_generation' %}">试卷管理</a></li>

				</ul>
            </li>
		</ul>
	</div>
	<div class="clearfix"></div>
</div>


<!--js -->
<script src="{% static 'online_test/js/jquery.nicescroll.js' %}"></script>
<script src="{% static 'online_test/js/scripts.js' %}"></script>
<!-- Bootstrap Core JavaScript -->
<script src="{% static 'online_test/js/bootstrap.min.js' %}"></script>
<!-- /Bootstrap Core JavaScript -->
<!-- real-time -->


<script src="{% static 'online_test/js/menu_jquery.js' %}"></script>
</body>

</html>